
// Field descriptions for admin tooltips - mirrors the descriptions used by AI
export const propertyFieldDescriptions = {
  // ATTOM Address fields
  attom_sell_property_address_street: "Street address from ATTOM Data API",
  attom_sell_property_address_city: "City name from ATTOM Data API",
  attom_sell_property_address_state: "State abbreviation from ATTOM Data API",
  attom_sell_property_address_zip: "ZIP code from ATTOM Data API",
  attom_sell_property_address_country: "Country from ATTOM Data API",
  attom_sell_property_subdvision_name: "Subdivision/neighborhood name from ATTOM",
  attom_sell_property_municipality_name: "Municipality name from ATTOM",
  attom_sell_property_county: "County name from ATTOM Data API",
  
  // Property details from ATTOM
  attom_sell_property_use_type: "Property type classification (Single Family, Condo, etc.)",
  attom_sell_property_year_built: "Year the property was constructed",
  attom_sell_property_levels: "Number of stories/levels in the building",
  attom_sell_property_finished_sf: "Finished square footage of living space",
  attom_sell_property_siding: "Exterior siding/wall material type",
  attom_sell_property_roof_type: "Type of roofing material",
  attom_sell_property_central_air: "Central air conditioning system type",
  attom_sell_property_heating_type: "Primary heating system type",
  attom_sell_property_heating_fuel_type: "Fuel type used for heating",
  attom_sell_property_fireplace_number: "Number of fireplaces in the property",
  attom_sell_property_lot_size: "Size of the property lot in square feet",
  attom_sell_property_lot_zoning: "Zoning classification for the lot",
  attom_sell_property_mortgage_amount: "Primary mortgage amount from ATTOM",
  attom_sell_property_2nd_mortgage_amount: "Second mortgage amount from ATTOM",
  attom_sell_property_has_conservation_easement: "Conservation easement status",
  attom_sell_property_architectural_style: "Architectural style of the building",
  attom_sell_property_water_source: "Primary water source type",
  attom_sell_property_sewer_type: "Sewer system type",
  attom_sell_property_pool_type: "Swimming pool type if present",
  attom_sell_property_garage: "Garage type and capacity",
  attom_sell_property_flooring_types: "Types of flooring materials used",
  attom_sell_property_taxes: "Annual property tax amount",
  attom_sell_property_designated_historic: "Historic designation status",
  
  // School fields
  attom_sell_property_school_district: "Primary school district name",
  attom_sell_property_school_district_elementary: "Elementary school name",
  attom_sell_property_school_district_middle: "Middle school name",
  attom_sell_property_school_district_high: "High school name",
  
  // Legal and tax fields
  attom_property_legal_description1: "First line of legal property description",
  attom_property_legal_description2: "Second line of legal property description",
  attom_property_legal_description3: "Third line of legal property description",
  attom_property_tax_id: "Official property tax identification number",
  
  // App fields (user-entered data)
  app_address: "Full address as entered by user",
  app_street: "Street address component",
  app_city: "City component",
  app_state: "State component",
  app_zip_code: "ZIP code component",
  app_image_url: "URL of the main property image",
  app_estimated_value: "Estimated property value",
  app_property_type: "Property type classification",
  app_bedrooms: "Number of bedrooms",
  app_bathrooms: "Number of bathrooms",
  
  // User info fields
  app_owner_user_id: "Internal user ID of property owner",
  app_first_name: "Property owner's first name",
  app_last_name: "Property owner's last name",
  app_email: "Property owner's email address",
  app_phone: "Property owner's phone number",
  app_is_buying_home: "Whether user is also buying a new home",
  app_referred_by: "Referral source or referrer ID",
  
  // ATTOM ID
  attom_id: "Unique ATTOM Data property identifier",
  
  // Linking fields
  app_user_link: "Link to user record in Users table",
  property_id: "Internal property identifier",
  Conversations: "Link to conversation records for this property"
};

export const propertyIntakeFieldDescriptions = {
  "seller_1_mailing_address": "Address (What is your mailing address?) This is the user's street and number of the user's address which mail will be sent to",
  "sell_property_exterior_features": "Any of these exterior features present? Indicates whether there are a selection of exterior features present, either a deck, patio, pool, retractable awning, hot tub, Intercom, Storm Doors, or Storm windows",
  "sell_property_hoa_pets": "Are pets allowed by the HOA? Indicates whether pet are allowed, they are either allowed, only some are allowed, they are not allowed, or they are not sure.",
  "sell_property_items_not_included": "Are there any appliances or features that have been checked off that are NOT included with the sale of the home? Indicates whether there are appliances that are checked off that are not included in the sale of the house",
  "sell_property_liens_other": "Are there any liens, judgments, or legal matters tied to the property? Indicates whether there are any liens, judgements, or legal matters tied to the property, either a Tax lien, a Mechanics lien, a judgement lien, A HOA lien, a child support or alimony lien, a municipal lien, a bankruptcy, or none. The owner can indicate that they are not sure",
  "sell_property_additional_structures": "Are there any other structures on the property? Indicates whether there is another structure on the property, either an Additional Dwelling Unit, Stable / Horse barn, a Barn, a workshop, a shed, a gazebo, a greenhouse, a playground or a treehouse.",
  "know_sell_property_hidden_defects": "Are you aware of any hidden defects in the property that are not visible or discoverable during a normal inspection that could significantly affect the property's value, safety, or usefulness? Indicates whether the owner knows of any defects which are observable on a normal inspection which impact the home's price",
  "seller_pay_buyer_agent_commission": "Are you willing to pay a buyer's agent commission? Indicates whether a seller is willing to pay a buyers agent commission (The fee paid to the real estate agent representing the buyer)",
  "seller_pay_buyer_agent_closing_amount": "How much are you willing to pay? Indicates the amount a seller is willing to pay in a buyers agent commission",
  "sell_property_bulkhead_type": "Bulkhead built along the shoreline? Indicates whether there is a bulkhead built along the shoreline, either There is no bulkhead or there is and its made out of wood, concrete, vinyl, steel sheet piling, or stone.",
  "sell_property_interior_features": "Check off any of these features that are included in the sale of the property Indicates if the following features are included in the sale of the property, a sunroom, a sauna, heated floors, a walk in gun safe, a wine cellar, a home theater, a library, a wet bar, a mudroom, a loft, hidden rooms, an elevator, an alarm system, ceiling fans, central vacuum, a clothes dryer, a clothes washer, curtain rods, electronic air filters, exhaust fans, a freezer, a furnace humidifier, Window screens, wall mount TV brackets, a water filler, or a water softener",
  "sell_property_kitchen_features": "Check off any of these kitchen features. Indicates if any of the following kitchen features are present, Granite countertops, quartz countertops, marble countertops, butcher block countertops, an island, stainless steel appliances, a wine fridge, a gas stove, a double oven, a microwave, a dishwasher, a wine fridge, a garbage disposal, under cabinet lighting, Breakfast bar or eat-in area, open-concept, smart appliances, a walk in pantry, soft close drawers/doors, pull out shelves/lazy Susan, or a refrigerator",
  "sell_property_address_city": "City (What is the full address of the property you intend to sell?) This is the address(city) of the property which the user intends to sell",
  "seller_1_mailing_address_city": "City (What is your mailing address?) This is the city of the user's address which mail will be sent to",
  "sell_property_address_country": "Country (What is the full address of the property you intend to sell?) This is the address(country) of the property which the user intends to sell",
  "seller_1_mailing_address_country": "Country (What is your mailing address?) This is the country of the user's address which mail will be sent to",
  "know_seller_desired_listing_price": "Do you already have an idea of how much you want to list your home for? Indicates whether the seller has an idea for the listing price of the house",
  "sell_property_mortgage": "Do you have a mortgage on the home? Indicates whether the property is under mortgage, either it is not, it is, it is and the owner has a second mortgage on the house",
  "sell_property_listing_timeframe": "Do you have a timeline or deadline for selling? Indicates the timeline/deadline for selling the property",
  "know_sell_property_water_depth": "Do you know how deep the water is at Mean Low Water depth? Indicates whether the owner knows how deep the water is at mean low water depth, either Yes due toe measurement, Yes due to tide charts, No, but they can provide an estimate, or the owner does not know",
  "know_sell_property_taxes": "Do you know how much the property taxes are annually? Indicates whether the user knows how expensive property taxes are annually",
  "know_sell_property_liens_other_amount": "How much do you owe towards the lien(s)? Gives an estimate of how much the owner owes to the lien",
  "know_sell_property_air_conditioning_age": "Do you know how old the air conditioning system is? Indicates whether the user knows how old the air conditioning system is.",
  "know_sell_property_furnace_age": "Do you know how old the furnace is? Indicates whether the user knows how old the furnace is.",
  "know_sell_property_heat_pump_age": "Do you know how old the heat pump is? Indicates if the owner knows how old the heat pump is.",
  "know_sell_property_roof_age": "Do you know how old the roof is? Indicates whether the owner knows how old the roof is.",
  "know_sell_property_water_heater_age": "Do you know how old your water heater is? Indicates how old the water heater on the house to be sold is.",
  "sell_property_fire_retardant_wood": "Do you know if your house was constructed with fire retardant treated wood? Indicates whether the owner knows if the house was constructed with fire retardant wood.",
  "know_sell_property_adu_sf": "Do you know the square footage of the Additional Dwelling Unit? Indicates whether the owner knows the square footage of the Additional Dwelling unit",
  "know_sell_property_finished_sf": "Do you know the square footage of the house? Indicates whether the homeowner knows the square footage of the house",
  "know_sell_property_year_built": "Do you know what year the house was built? Indicates whether the user knows the year in which the house to be sold was built",
  "know_sell_property_listing_date": "Do you know when you'd like to put your house on the market? Indicates if the seller knows when they want to list their house on the market",
  "know_sell_property_school_district": "Do you know which school district and school boundaries your property is in? Indicates which school district and which school boundary the property is located in",
  "sell_property_leased_items": "Do you lease any of the following? Indicates whether the owner leases a Fuel Tank(s), Solar Panels, an Alarm System, a water treatment system, or something else",
  "second_individual_owner": "Does anyone else own the property that you're selling? This determines if there are co-owners to the property",
  "sell_property_basement_exit": "Does the basement have an exterior exit? Indicates whether the basement has an exit to the exterior.",
  "sell_property_hoa_recreation_fee": "Does the HOA charge a separate recreation fee? Indicates whether the HOA charges a Recreation fee(A fee for neighborhood upkeep or renovations)",
  "sell_property_central_air": "Does the home have central air conditioning? Indicates whether the house has central air conditioning. If not, the owner can indicate that they have either Ductless mini split A/C units, window units, or no air conditioning at all. The owner can indicate they do not know.",
  "sell_property_garage": "Does the property have a garage? Indicates whether the property has a garage",
  "sell_property_views": "Does the property have any notable views? Does the property have any noticeable views, namely a wooded view, mountain view, open field or pasture view, golf course view, park or green space view, sunrise or sunset view, or something else.",
  "sell_property_lot_features": "Does the property have any of these lot features? Indicates if the property has any of these features, Back to Trees, Level Yards, Corner Lots, Cul-de-sac Location, Fenced Yard, Backs to Open Space, Sloped or Terraced Lot, Flag Lot, Garden or Landscaped areas, or an Irrigation System.",
  "sell_property_parking_space_number": "Estimate the total parking spaces are available on the property. Indicates the estimated number of parking spaces on the property",
  "seller_next_home_plans": "Have you already purchased or identified your next home? Indicates whether the owner of the house already has purchased their next property",
  "obligated_perform_lead_treatment": "Have you been obligated to perform either the modified or full risk reduction treatment of the property under the Maryland Lead Poisoning Prevention Program? Indicated whether the current owner has been forced to preform the modified or full risk reduction treatment for lead due to the Maryland Lead Poisoning Prevention Program?",
  "sell_property_lead_hazards": "Have you or anyone else noticed the existence of lead based paint hazards or noticed elevated blood lead levels from a tenant, or state, local, or municipal health agency? Indicates whether lead based paint is present, or if elevated lead levels in the bloodstream have been noticed.",
  "sell_property_over_garage_apartment_baths": "How many bathrooms are in the apartment over the garage? Indicates the number of bathrooms in the over garage apartment",
  "sell_property_over_garage_apartment_beds": "How many bedrooms are in the apartment over the garage? Indicates the number of bedrooms that are in the over garage apartment",
  "sell_property_ceiling_fan_number": "How many ceiling fans are in your home? Indicates how many ceiling fans are in the house",
  "seller_rent_back_days": "How many days would you like to live in your property after selling it? This number is the number of days that the seller(s) would like to stay in their home and rent back from the buyers. Include this information in Post Settlement Occupancy Agreement (MAR) and Post-Settlement Occupancy Addendum (GCAAR 1309)",
  "sell_property_exhaust_fan_number": "How many exhaust fans are in your home? Indicates the number of exhaust fans are in the home",
  "know_sell_property_water_depth_low": "How many feet deep is the water at Mean Low Water (MLW) depth? Indicates how many feet deep the water is at mean low water",
  "know_sell_property_water_depth_from_pier": "How many feet deep is the water at the end of the pier at Mean Low Water (MLW) depth? Indicates how many feet deep the water at the end of the pier at mean low water depth is",
  "sell_property_fireplace_number": "How many fireplaces does the home have? Indicates the number of fireplaces on the house which is being sold",
  "sell_property_garage_opener_remote_control_number": "How many garage door opener remote controls are there? Indicates how many garage door opener remote controllers there are.",
  "sell_property_garage_opener_number": "How many garage door openers are there? Indicates how many garage door openers there are",
  "seller_showing_notice": "How many hours notice do you need before showings? Indicates how much notice a seller needs before a potential buyers views the house",
  "sell_property_levels": "How many levels does the home have? (Don't include a basement) Indicates the amount of floors a house has, not including basement.",
  "sell_property_refrigerator_number": "How many refrigerators are there? Indicates how many refrigerators there are in the house",
  "sell_property_barn_number": "How many stables / barns are there? Indicates how many barns there are on the property",
  "sell_property_shed_number": "How many storage sheds are there? Indicates how many storage sheds there are",
  "sell_property_taxes": "How much are the property taxes annually? Indicates how expensive property taxes are annually",
  "sell_property_2nd_mortgage_amount": "How much do you owe on the 2nd mortgage / HELOC? Indicates how much the owner owes on the second mortgage on the house",
  "sell_property_mortgage_amount": "How much do you owe on the mortgage? Indicates how much the owner owes on the mortgage on the house",
  "annual_ground_rent": "How much is the Ground Rent annually? The annual amount the property owner pays to the landowner for using the land (ground rent).",
  "sell_property_hoa_recreation_fee_amount": "How much is the separate HOA recreation fee? Indicates how much the Home owners recreation fee is",
  "seller_desired_listing_price": "How much would you like to list your property for? Indicates how much the seller wants to list the property for",
  "sell_property_air_conditioning_age": "How old is air conditioning system (in years)? Indicates how old the air conditioning system is.",
  "sell_property_furnace_age": "How old is the furnace (in years)? Indicates how old the furnace is, in years.",
  "sell_property_heat_pump_age": "How old is the heat pump (in years)? Indicates if the owner knows how old the heat pump is.",
  "sell_property_roof_age": "How old is the roof (in years)? Indicates how old the roof of the house is.",
  "sell_property_water_heater_age": "How old is the water heater (in years)? Indicates how old the water heater is on the house which is being sold",
  "seller_sale_timeline_preference": "How soon would you like to sell your property? Indicates how quickly the owner wants to sell the property",
  "sell_property_siding_condition": "How would you describe the condition of the siding? Indicates the condition of the siding of the house, either perfect, great, good, or poor.",
  "sell_property_garage_number": "If yes, how many garage spaces are there? Indicates how many garages there are",
  "sell_property_hoa_name": "If yes, what is the name of the HOA or association? Indicates the name of the association",
  "committed_to_perform_lead_remediations": "If you have not yet performed the treatment, will you perform the required treatment before selling the property to a buyer? If the owner is required to perform a lead treatment under the Maryland Lead Poisoning Prevention Program, will they perform it before selling the property.",
  "sell_property_year_built": "In what year was the home built? Indicates what year the house to be sold was built",
  "sell_property_water_access": "Is it close to water? Indicates if the property is close to water, the owner can select Water View only, Water access, waterfront, or not close to water.",
  "sell_property_conservation_easement_type": "Is it part of any of these conservation easements? Determines if the property is subject to any of the following conservation easements, Maryland Environmental Trust, Maryland Historical Trust, Maryland Agricultural Land Preservation Trust, Maryland Department of Natural Resources, A County or Municipal Corporation, funded by the Maryland Department of Natural Resources, the Rural Legacy Program, or a local Agricultural Preservation Program, Land Trust, or A conservation easement required by a permit issued by the Department of the Environment.",
  "sell_property_unfinished_basement_roughed_in": "Is rough-in plumbing for a future bathroom present? Indicates whether the plumbing(rough in plumbing) is present for a future bathroom.",
  "sell_property_basement_finished": "Is the basement finished? Is the house's basement finished",
  "sell_property_hoa_or_condo": "Is the home part of a homeowners or condo association? Indicates whether the house is part of a homeowners or condo association",
  "sell_property_designated_historic": "Is the property historically designated? Indicates whether the property is historically designated. The owner can select that they do not know",
  "sell_property_municipality": "Is the property located within city/municipality limits? Indicates whether the property being sold is located inside the official boundaries of a city or municipality (Yes/No).",
  "sell_property_water_navigable": "Is the water navigable? Indicates whether you can navigate through the water, the owner can indicate that they do not know.",
  "sell_property_pier": "Is there a pier? Indicates if there is a pier onto the water",
  "2nd_non_owner_contact": "Is there a secondary contact person (e.g. your spouse) who you'd like notified about this transaction? This determines if there is someone else who will be notified about the selling/buying of the property",
  "sell_property_pier_structures": "Is there a structure on the pier? Indicates whether there is a structure on the pier, the owner can indicate whether there is a Boat House, Dock House, Boat Lift or No Structure",
  "property_ownership_type": "Is there an individual(s), a trust, or a company on the title of the property you intend to sell? No description available",
  "sell_property_registered_MLPPP": "Is this property registered in the Maryland Lead Poisoning Prevention Program? Indicates whether the property is registered in the Maryland Lead Poisoning Prevention Program?",
  "sell_property_has_conservation_easement": "Is your property subject to a Conservation Easement? Indicates whether the property is legally restricted by a conservation easement.",
  "1_mile_from_super_fund_site": "Is your property within 1 mile of any of these locations? Determines if the property being sold is within any of the following locations, Indian Head Naval Surface Warfare Center (Charles County), Fort Detrick Area B Ground Water (Frederick County), Aberdeen Proving Ground (Edgewood Area) , Aberdeen Proving Ground (Michaelsville Landfill) (Harford County), Bush Valley Landfill (Harford County), Andrews Air Force Base (Prince George’s County), Beltsville Agricultural Research Center (Prince George’s County), Brandywine Defense Reutilization & Marketing Office (Prince George's County), Patuxent River Naval Air Station (St. Mary's County)",
  "sell_property_leased_items_details": "Please explain further. What do you lease and from whom? Indicates what specifically the owner leases and from where.",
  "sell_property_hidden_defects": "Please explain. What significant, hidden defects does your house have? Indicates what the defects are in the house that are significant but hidden.",
  "sell_property_address_state": "State/Province (What is the full address of the property you intend to sell?) This is the address(state/Province) of the property which the user intends to sell",
  "seller_1_mailing_address_state": "State/Province (What is your mailing address?) This is the state of the user's address which mail will be sent to",
  "sell_property_water_type": "Type of water? What is the type of water is the property close to, Ocean, Bay, River, Creek, Lake or Pond",
  "sell_property_architectural_style": "What architectural style is most like the property? Determines the style of the house being sold, either Cape Cod, Colonial, Ranch(Rambler), Craftsman(Bungalow), Tundor Revival, Victorian / Queen Anne, Modern / Contemporary, Shingle Style, Farmhouse / Modern Farmhouse",
  "sell_property_heating_fuel_type": "What are the fuel sources for your heating system(s)? Indicates what the fuel source for the heating system is, Natural Gas, Propane, Electricity, Oil, Wood, or Pellets. The user can indicate that they do not know.",
  "sell_property_hoa_annual_fee": "What are the HOA and/or condo fees annually? Indicates what the Home owners or condo association fees are annually",
  "sell_property_utility_providers": "What are the names of your utility providers? Indicates the name of the utility provider the house uses.",
  "sell_property_pool_condition": "What condition is the pool in? Indicates the condition of the pool, either excellent, great, good, poor, or not functional",
  "sell_property_county": "What county is the property located in? This is the county in which the property which is being sold is located",
  "sell_property_water_heater_fuel_type": "What fuel source does your water heater use? Indicates the fuel source of the water heater the home has, either Electric, Natural Gas, Propane, or Oil. The owner can indicate that they are not sure.",
  "sell_property_school_district_elementary": "What is the assigned public elementary school? Indicates the assigned public elementary school for the property",
  "sell_property_school_district_high": "What is the assigned public high school? Indicates the assigned public high school for the property",
  "sell_property_school_district_middle": "What is the assigned public middle school? Indicates the assigned public middle school for the property",
  "sell_property_air_fuel": "What is the fuel source for the air conditioning system? Indicates whether the owner knows what fuel source the air conditioner uses, either Electricity or Natural gas. The owner can indicate they don't know.",
  "sell_property_lot_size": "What is the lot size in acres? No description available",
  "sell_property_subdivision_name": "What is the name of the neighborhood or subdivision (if any)? This is the name of the neighborhood or subdivision which the house is located",
  "sell_property_school_district": "What is the public school district the property belongs to? Indicates which public school district the property belongs to",
  "sell_property_adu_sf": "What is the square footage of the Additional Dwelling Unit? Indicates the square footage of the Additional Dwelling Unit",
  "sell_property_finished_sf": "What is the square footage of the house? Indicates the square footage of the house",
  "sell_property_over_garage_apartment_sf": "What is the square footage of the over-garage apartment? Indicates the square footage of the over garage apartment",
  "trust_or_company_name": "What is the trust or company's name? This is the name of the company or trust which owns the property",
  "sell_property_lot_zoning": "What is the zoning designation for this property? Indicates the zoning designation for the property, either Residential, Commercial, Agricultural, Mixed use, or industrial. The owner can indicate that they do not know.",
  "seller_2_email_address": "What is your co-seller's email address? This is the email address of the co-owner of the house",
  "seller_2_first_name": "What is your co-seller's first name? This is the first name of the co-owner of the house",
  "seller_2_last_name": "What is your co-seller's last name? This is the last name of the co-owner of the house",
  "seller_2_phone_number": "What is your co-seller's phone number? This is the cell phone number of the co-owner of the house",
  "seller_1_email_address": "What is your email address? This is the email address of the user",
  "seller_1_first_name": "What is your first name? This is the first name of the user",
  "seller_1_last_name": "What is your last name? This is the last name of the user",
  "seller_1_phone_number": "What is your phone number? This is the telephone number of the user",
  "contact_2_email_address": "What is your secondary contact person's email address? This is the email address of the secondary person who will be notified about the buying/selling of the property",
  "contact_2_first_name": "What is your secondary contact person's first name? This is the first name of the secondary person who will be notified about the buying/selling of the property",
  "contact_2_last_name": "What is your secondary contact person's last name? This is the last name of the secondary person who will be notified about the buying/selling of the property",
  "contact_2_phone_number": "What is your secondary contact person's phone number? This is the phone number of the secondary person who will be notified about the buying/selling of the property",
  "sell_property_foundation": "What kind of foundation does the home have? Indicates the type of foundation the home have, either a Slab, Crawlspace, or basement foundation. The owner can indicate that they do not know.",
  "sell_property_pool_type": "What kind of pool is it? Indicates whether the pool is above or below ground",
  "sell_property_residence_type": "What kind of property is this for you? Indicates the type of property it is in relation to the owner, whether a primary residence, a vacation home, or an investment property",
  "sell_property_municipality_name": "What municipality is the property in? This indicates the name of the municipality in which the property being sold is located",
  "sell_property_other_views": "What other notable views does the property have? Indicates whether the property has a unique notable view.",
  "seller_showing_availability_start_time": "What time can buyers start viewing the property? Indicates what time of the day the potential buyers can view the property",
  "seller_showing_availability_end_time": "What time may buyers no longer view the property? Indicates what time of the day potential buyers must stop viewing the property",
  "obligated_perform": "What treatment were you obligated to perform on the property? Indicates what past treatments were performed on the property",
  "sell_property_heating_type": "What type of heating system does the home use? Indicates what type of heating the owner has, Forced Air Furnace, Boiler, Heat Pump, Radiant Floor Heating, Electric Baseboard, Wood/Pellet stove, Gas Stove or Fireplace, Wood Fireplace, No Heating system. The user can indicate they do not know.",
  "sell_property_use_type": "What type of property is it? Determines what type of house is being sold, either Detached (SFH), Attached (Townhouse), Duplex, Triplex, 4-Plex, Multi-Family, Condo, Manufactured Home or, Modular Home",
  "sell_property_roof_type": "What type of roof does the property have? Indicates the type of roof the house to be sold has, Asphalt Shingles, Metal Roofing, Wood Shingles or Shakes, Clay or Concrete Tile, Slate, Synthetic Shingles, or Flat Roofing (e.g., TPO, EPDM, Built-Up). The owner can indicate they do not know.",
  "sell_property_sewer_type": "What type of sewer system does the home use? Indicates what type of sewer system the house uses, either a public system, a septic system, or a community/shared septic system. The owner can indicate that they do not know.",
  "sell_property_siding": "What type of siding do you have? Indicates which type of siding the house has, either Brick, Vinyl, Wood, Fiber Cement, Stucco, Natural Stone, Manufactured Stone, Aluminum Siding, or Concrete block. The owner can indicate that they do not know.",
  "sell_property_water_heater_type": "What type of water heater does the home use? Indicates the type of water heater the home has, either a Storage Tank, Tankless, or no functioning water heater. The owner can indicate that they do not know.",
  "sell_property_flooring_types": "What types of flooring are in the home (e.g., hardwood, carpet, tile)? Indicates the types of flooring in the home, either Hardwood, bamboo, laminate, Luxury Vinyl Plank, Vinyl Tile, Tile, Stone, Concrete, or carpet.",
  "sale_type": "What's being sold? Indicates what part of the property is being sold, the The house & the land (Fee Simple), Land Only (There's no house on the property), or Just a house, but not the land (Has Ground Rent)",
  "seller_reason_to_sell": "What’s prompting your decision to sell now? Indicates the reason for the property being sold",
  "seller_timeline_to_sell": "When do you think you'll be ready to put your house on the market? Indicates when the seller is willing to list their house on the market(1-2 months, 3-4 months, 4-6 months, 6-12 months, 1-2 years)",
  "seller_showing_availability_days": "When listing is published, which days can buyers view the property? Indicates when potential buyers of the property can view it",
  "sell_property_listing_date": "When would you like to put your property on the market? Indicates when the seller wants to list their house on the market",
  "sell_property_laundry_hookup_location": "Where are the laundry hookups located? Indicates where the laundry hookups are located in the house, either in the upper level, main level, or the basement",
  "sell_property_water_source": "Where does the home get its water? Indicates from where the house gets its water, either public water, a private well, or a shared well. The user can also indicate they do not know.",
  "sell_property_garage_features": "Which garage features are present? Indicates whether the following features are present in the garage, whether it is attached or detached, whether it has a side entry, an automatic garage door opener, an over garage apartment, Car Lift",
  "sell_property_occupancy_type": "Will you be living in the home after it's been listed on the market? Indicates whether the owner will live in the house after it is listed on the market",
  "seller_rent_back_plans": "Would you like to \"rent back\" from the buyer? Indicates whether the owner will \"rent back\" from the buyer after the closing of the sale",
  "sell_property_address_zip": "Zip/Postal code (What is the full address of the property you intend to sell?) This is the address(zip/postal code) of the property which the user intends to sell",
  "seller_1_mailing_address_zip": "Zip/Postal code (What is your mailing address?) This is the zip code of the user's address which mail will be sent to"
};
